#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.1 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Mar 11 14:22:29 CET 2020
# SW Build 2188600 on Wed Apr  4 18:39:19 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axis_infrastructure_v1_1_0 fifo_generator_v13_2_2 axis_data_fifo_v1_1_17 lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_18 xlconstant_v1_1_4 xlconcat_v2_1_1 xbip_utils_v3_0_9 c_reg_fd_v12_0_5 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_5 xbip_dsp48_addsub_v3_0_5 xbip_addsub_v3_0_5 c_addsub_v12_0_12 c_gate_bit_v12_0_5 xbip_counter_v3_0_5 c_counter_binary_v12_0_12 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_16 axi_data_fifo_v2_1_15 axi_crossbar_v2_1_17 smartconnect_v1_0 axi_protocol_checker_v2_0_2 axi_vip_v1_1_2 zynq_ultra_ps_e_vip_v1_0_2 axi_protocol_converter_v2_1_16 axi_clock_converter_v2_1_15 blk_mem_gen_v8_4_1 axi_dwidth_converter_v2_1_16)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2018.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/opt/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v1_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/36f8/hdl/axis_data_fifo_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_data_fifo_0_0/sim/design_1_axis_data_fifo_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/sim/design_1_rst_processing_system7_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_proc_sys_reset_0_0/sim/design_1_proc_sys_reset_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_proc_sys_reset_0_1/sim/design_1_proc_sys_reset_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_data_fifo_1_0/sim/design_1_axis_data_fifo_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_18 $vhdlan_opts \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/fbf9/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_0_0/sim/design_1_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/2fc9/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_0/sim/design_1_xlconstant_0_0.v" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/6b63/hdl/verilog/LF_valid_to_AXIS.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_LF_valid_to_AXIS_0_0/sim/design_1_LF_valid_to_AXIS_0_0.v" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/3b76/hdl/verilog/ov7670_interface.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_ov7670_interface_0_1/sim/design_1_ov7670_interface_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_1_0/sim/design_1_axi_gpio_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_1/sim/design_1_xlconstant_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_0_1/sim/design_1_xlconcat_0_1.v" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/23a8/hdl/verilog/axis_to_ddr_writebkb.v" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/23a8/hdl/verilog/axis_to_ddr_writer_AXILiteS_s_axi.v" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/23a8/hdl/verilog/axis_to_ddr_writer_base_ddr_addr_m_axi.v" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/23a8/hdl/verilog/axis_to_ddr_writer.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_to_ddr_writer_0_0/sim/design_1_axis_to_ddr_writer_0_0.v" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/b680/hdl/verilog/ddr_to_axis_readebkb.v" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/b680/hdl/verilog/ddr_to_axis_reader_AXILiteS_s_axi.v" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/b680/hdl/verilog/ddr_to_axis_reader_base_ddr_addr_m_axi.v" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/b680/hdl/verilog/ddr_to_axis_reader.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_ddr_to_axis_reader_0_1/sim/design_1_ddr_to_axis_reader_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/a5f8/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_5 $vhdlan_opts \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/cbdd/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/da55/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/442e/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad9e/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0e42/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/7f1a/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_5 $vhdlan_opts \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/693f/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0952/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/c366/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_c_counter_binary_0_0/sim/design_1_c_counter_binary_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/cfa3/hdl/verilog/ov7670_LUMA_CHROMA.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_ov7670_LUMA_CHROMA_0_0/sim/design_1_ov7670_LUMA_CHROMA_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_2/sim/design_1_xlconstant_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_to_ddr_writer_1_0/sim/design_1_axis_to_ddr_writer_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_to_ddr_writer_2_0/sim/design_1_axis_to_ddr_writer_2_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_data_fifo_0_2/sim/design_1_axis_data_fifo_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_data_fifo_1_2/sim/design_1_axis_data_fifo_1_2.v" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/5494/hdl/verilog/ddr_to_axis_readebkb.v" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/5494/hdl/verilog/ddr_to_axis_reader_SD_AXILiteS_s_axi.v" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/5494/hdl/verilog/ddr_to_axis_reader_SD_base_ddr_addr_m_axi.v" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/5494/hdl/verilog/ddr_to_axis_reader_SD.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_ddr_to_axis_reader_SD_0_0/sim/design_1_ddr_to_axis_reader_SD_0_0.v" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/f591/hdl/verilog/mux_sd_ov_AXILiteS_s_axi.v" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/f591/hdl/verilog/mux_sd_ov.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_mux_sd_ov_1_0/sim/design_1_mux_sd_ov_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0cde/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/d114/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/d293/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_2/sim/design_1_xbar_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_1/sim/design_1_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_2 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/3755/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_2 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/725c/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_2 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim/design_1_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
    "$ref_dir/../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/1229/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/d371/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/2c2b/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl" +incdir+"/opt/Xilinx/Vivado/2018.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_6/sim/design_1_auto_ds_6.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_6/sim/design_1_auto_pc_6.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_5/sim/design_1_auto_ds_5.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_5/sim/design_1_auto_pc_5.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_4/sim/design_1_auto_ds_4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_4/sim/design_1_auto_pc_4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_3/sim/design_1_auto_ds_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_3/sim/design_1_auto_pc_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_2/sim/design_1_auto_ds_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_2/sim/design_1_auto_pc_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_1/sim/design_1_auto_ds_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_4/sim/design_1_auto_us_4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_0/sim/design_1_auto_ds_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_3/sim/design_1_auto_us_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_2/sim/design_1_auto_us_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_1/sim/design_1_auto_us_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_us_0/sim/design_1_auto_us_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/kidre/Documenti/Università/Uni/Tesi/OV7670_Ultra+/OV7670_2018.1.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
