# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-29381-kidre-N551JX/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xczu3eg-sbva484-1-e

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903
    /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl
    /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl
    /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl
  } {
      /media/kidre/8a0a81cd-859e-4c75-9e65-2b4a729982e4/opt/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /media/kidre/8a0a81cd-859e-4c75-9e65-2b4a729982e4/opt/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /media/kidre/8a0a81cd-859e-4c75-9e65-2b4a729982e4/opt/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/4903
    /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl
    /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl
    /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad7b/hdl
  } {
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl/axis_infrastructure_v1_1_vl_rfs.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/36f8/hdl/axis_data_fifo_v1_1_vl_rfs.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_1_0/synth/design_1_axis_data_fifo_1_0.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/2fc9/hdl/xlconstant_v1_1_vl_rfs.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_0_0/synth/design_1_xlconstant_0_0.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/6b63/hdl/verilog/LF_valid_to_AXIS.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_LF_valid_to_AXIS_0_0/synth/design_1_LF_valid_to_AXIS_0_0.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/3b76/hdl/verilog/ov7670_interface.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_ov7670_interface_0_1/synth/design_1_ov7670_interface_0_1.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_0_1/synth/design_1_xlconstant_0_1.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_xlconcat_0_1/synth/design_1_xlconcat_0_1.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/23a8/hdl/verilog/axis_to_ddr_writebkb.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/23a8/hdl/verilog/axis_to_ddr_writer_AXILiteS_s_axi.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/23a8/hdl/verilog/axis_to_ddr_writer_base_ddr_addr_m_axi.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/23a8/hdl/verilog/axis_to_ddr_writer.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_axis_to_ddr_writer_0_0/synth/design_1_axis_to_ddr_writer_0_0.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/b680/hdl/verilog/ddr_to_axis_readebkb.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/b680/hdl/verilog/ddr_to_axis_reader_AXILiteS_s_axi.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/b680/hdl/verilog/ddr_to_axis_reader_base_ddr_addr_m_axi.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/b680/hdl/verilog/ddr_to_axis_reader.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_ddr_to_axis_reader_0_1/synth/design_1_ddr_to_axis_reader_0_1.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/cfa3/hdl/verilog/ov7670_LUMA_CHROMA.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_ov7670_LUMA_CHROMA_0_0/synth/design_1_ov7670_LUMA_CHROMA_0_0.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_0_2/synth/design_1_xlconstant_0_2.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_axis_to_ddr_writer_1_0/synth/design_1_axis_to_ddr_writer_1_0.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_axis_to_ddr_writer_2_0/synth/design_1_axis_to_ddr_writer_2_0.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_2/synth/design_1_axis_data_fifo_0_2.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_1_2/synth/design_1_axis_data_fifo_1_2.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0cde/hdl/axi_register_slice_v2_1_vl_rfs.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/d114/hdl/axi_data_fifo_v2_1_vl_rfs.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/d293/hdl/axi_crossbar_v2_1_vl_rfs.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/synth/design_1_xbar_0.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/synth/design_1_xbar_1.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/hdl/zynq_ultra_ps_e_v3_2_0.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/synth/design_1_zynq_ultra_ps_e_0_0.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/synth/design_1.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/1229/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/d371/hdl/axi_clock_converter_v2_1_vl_rfs.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/2c2b/hdl/axi_dwidth_converter_v2_1_vlsyn_rfs.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_5/synth/design_1_auto_ds_5.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_5/synth/design_1_auto_pc_5.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_4/synth/design_1_auto_ds_4.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_4/synth/design_1_auto_pc_4.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_3/synth/design_1_auto_ds_3.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3/synth/design_1_auto_pc_3.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_2/synth/design_1_auto_ds_2.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_2/synth/design_1_auto_pc_2.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_1/synth/design_1_auto_ds_1.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/synth/design_1_auto_pc_1.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/synth/design_1_auto_ds_0.v
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/synth/design_1_auto_pc_0.v
    }
      rt::read_vhdl -lib lib_cdc_v1_0_2 /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_12 /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/synth/design_1_rst_processing_system7_0_100M_0.vhd
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/synth/design_1_proc_sys_reset_0_0.vhd
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_1/synth/design_1_proc_sys_reset_0_1.vhd
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/synth/design_1_axi_gpio_0_0.vhd
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/synth/design_1_axi_gpio_1_0.vhd
      /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ip/design_1_c_counter_binary_0_0/synth/design_1_c_counter_binary_0_0.vhd
    }
      rt::read_vhdl -lib blk_mem_gen_v8_4_1 /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/67d8/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_2 /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/7aff/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib interrupt_control_v3_1_4 /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_gpio_v2_0_18 /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/fbf9/hdl/axi_gpio_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_utils_v3_0_9 /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/a5f8/hdl/xbip_utils_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib c_reg_fd_v12_0_5 /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/cbdd/hdl/c_reg_fd_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_wrapper_v3_0_4 /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/da55/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_pipe_v3_0_5 /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/442e/hdl/xbip_pipe_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_addsub_v3_0_5 /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/ad9e/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_addsub_v3_0_5 /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0e42/hdl/xbip_addsub_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib c_addsub_v12_0_12 /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/7f1a/hdl/c_addsub_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib c_gate_bit_v12_0_5 /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/693f/hdl/c_gate_bit_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_counter_v3_0_5 /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/0952/hdl/xbip_counter_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib c_counter_binary_v12_0_12 /home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.srcs/sources_1/bd/design_1/ipshared/c366/hdl/c_counter_binary_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib xpm /media/kidre/8a0a81cd-859e-4c75-9e65-2b4a729982e4/opt/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-29381-kidre-N551JX/realtime/design_1_wrapper_synth.xdc
    rt::sdcChecksum
    set rt::top design_1_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/home/kidre/Immagini/Università/Uni/Tesi/Ultra96-/OV7670_Ultra+/OV7670_2018.1.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-29381-kidre-N551JX/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
